# permissions for end users to view dwoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dwoperator-viewer-role
rules:
- apiGroups:
  - operator.demo.dw.io
  resources:
  - dwoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.demo.dw.io
  resources:
  - dwoperators/status
  verbs:
  - get
