---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.demo.dw.io
  resources:
  - dwoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.demo.dw.io
  resources:
  - dwoperators/finalizers
  verbs:
  - update
- apiGroups:
  - operator.demo.dw.io
  resources:
  - dwoperators/status
  verbs:
  - get
  - patch
  - update
