apiVersion: operator.demo.dw.io/v1
kind: DwOperator
metadata:
  name: dwoperator-sample-default
  namespace: default
spec:
  name: dw-sample-default
  namespace: default
  replicas: 2

---

apiVersion: operator.demo.dw.io/v1
kind: DwOperator
metadata:
  name: dwoperator-sample-test1
  namespace: test1
spec:
  name: dw-sample-test1
  namespace: test1
  replicas: 2

---

apiVersion: operator.demo.dw.io/v1
kind: DwOperator
metadata:
  name: dwoperator-sample-test2
  namespace: test2
spec:
  name: dw-sample-test2
  namespace: test2
  replicas: 2
